# Dockerfile Units
# Create a Dockerfile from units.
#
# Copyright (C) 2023 - present Goytin Services Ltd.
# Written by Vladik Goytin.

ROOTDIR ?=			$(CURDIR)

.SHELLFLAGS :=			-ec
.ONESHELL:
MAKEFLAGS +=			--no-builtin-rules				\
				--no-builtin-variables				\
				--check-symlink-times				\
				--warn-undefined-variables			\
				--jobs=$(shell nproc)

TARGET :=			$(ROOTDIR)/Dockerfile
LIBDIR :=			$(ROOTDIR)/lib
SRCS :=				$(wildcard $(ROOTDIR)/*.dockerfileunit)		\
					$(wildcard $(LIBDIR)/*.dockerfileunit)	
TSTAMP :=			$(shell date +'%FT%H%M%S')
SQUEEZE_BLANK_LINES :=		'/\S/,/^\s*$$/!d'

all:				$(TARGET)

$(TARGET):			$(ROOTDIR)/Dockerfile.main $(SRCS) Makefile
	{ $(dockerfileunit_header); m4 --include=$(LIBDIR) < $<; } | \
		sed $(SQUEEZE_BLANK_LINES) > $@

define dockerfileunit_header
echo "# Generated by Dockerfile Units on $(TSTAMP)."
echo "#"
echo "# >>> DO NOT MODIFY! <<<"
echo 
endef

.PHONY: clean
clean:
	rm -f $(TARGET)
